export const ALL_DOGS = "ALL_DOGS";
export const GET_DETAIL = "GET_DETAIL";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_WEIGHT = "ORDER_BY_ WEIGHT";
export const FILTRED_CREATED = "FILTRED_CREATED";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const FILTER_TEMPERAMENT ="FILTER_TEMPERAMENT";
