# fly.toml app configuration file generated for dogs-pi on 2023-11-07T21:22:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dogs-pi"
primary_region = "eze"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
